export const PRODUCT_CATEGORIES = [
    "Electrónica",
    "Audio",
    "Wearables",
    "Fotografía y Video",
    "Informática",
    "Limpieza",
    "Dormitorio",
    "Cocina",
    "Iluminación",
    "Climatización",
    "Café y Bebidas",
    "Electrodomésticos de cocina",
    "Ciclismo",
    "Calzado deportivo",
    "Camping",
    "Entrenamiento",
    "Tenis",
    "Fútbol",
    "Juegos de mesa",
    "Movilidad Eléctrica",
    "Accesorios",
    "Gaming",
  ];
